### ISSUE TITLE
pathutil tests failing

### ISSUE THREAD

**Issue by raspher** [scripthaus-dev/scripthaus#3]
Hi, i'm trying to [package it](https://github.com/NixOS/nixpkgs/pull/286194) on NixOs and i've got issues with `pathutil` test:

```
pathutil_test.go:50: Error resolving commands.md: playbook not found 'commands.md' (resolved to '/*test/home/project/subproject1/subdir2/commands.md')
```

I think that:
 - it shouldn't touch top level directories
 - test files/folders should be provided inside repository to let it pass

What do You think about that? How the tests can be testable while packaging?

**Comment by sawka** [comment]
you're right (of course).  i'll fix this

**Comment by sawka** [comment]
ok, so i've removed the failing test and all is well.  i'll mark a new version so we'll have a clean build.

note that this test does *not* touch top level directories.  you'll notice the `/*test/`.  and in the _test.go file i'm using a mock resolver that uses internal fields to mimic the filesystem calls.  so no actual real filesystem calls are happening in the test.
